service: serverless-api
frameworkVersion: '>=1.28.0'
provider:
  name: aws
  runtime: go1.x
  region: us-east-1
  stage: ${opt:stage}
functions:
  api_function:
    handler: bin/main
    events:
      - http:
          path: /api
          method: GET
package:
  patterns:
    - '!*/**'
    - bin/main

